sudo: required
services:
  - docker

before_install:
  - docker build -t sjadon99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sjadon99/react-test npm test

after_success:
  - docker build -t sjadon99/multi-client ./client
  - docker build -t sjadon99/multi-nginx ./nginx
  - docker buils -t sjadon99/multi-server ./server
  - docker build -t sjadon99/multi-worker ./worker
